//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace LightSwitchApplication.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DiagnosticsData : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DiagnosticsData object using the connection string found in the 'DiagnosticsData' section of the application configuration file.
        /// </summary>
        public DiagnosticsData() : base("name=DiagnosticsData", "DiagnosticsData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DiagnosticsData object.
        /// </summary>
        public DiagnosticsData(string connectionString) : base(connectionString, "DiagnosticsData")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DiagnosticsData object.
        /// </summary>
        public DiagnosticsData(EntityConnection connection) : base(connection, "DiagnosticsData")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AuditTrail> AuditTrails
        {
            get
            {
                if ((_AuditTrails == null))
                {
                    _AuditTrails = base.CreateObjectSet<AuditTrail>("AuditTrails");
                }
                return _AuditTrails;
            }
        }
        private ObjectSet<AuditTrail> _AuditTrails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Endpoint> Endpoints
        {
            get
            {
                if ((_Endpoints == null))
                {
                    _Endpoints = base.CreateObjectSet<Endpoint>("Endpoints");
                }
                return _Endpoints;
            }
        }
        private ObjectSet<Endpoint> _Endpoints;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AuditTrails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuditTrails(AuditTrail auditTrail)
        {
            base.AddObject("AuditTrails", auditTrail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Endpoints EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEndpoints(Endpoint endpoint)
        {
            base.AddObject("Endpoints", endpoint);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="AuditTrail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AuditTrail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AuditTrail object.
        /// </summary>
        /// <param name="entityId">Initial value of the EntityId property.</param>
        /// <param name="entityType">Initial value of the EntityType property.</param>
        /// <param name="entityState">Initial value of the EntityState property.</param>
        /// <param name="original">Initial value of the Original property.</param>
        /// <param name="current">Initial value of the Current property.</param>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="tid">Initial value of the Tid property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="modifiedBy">Initial value of the ModifiedBy property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        /// <param name="modified">Initial value of the Modified property.</param>
        public static AuditTrail CreateAuditTrail(global::System.String entityId, global::System.String entityType, global::System.String entityState, global::System.String original, global::System.String current, global::System.Int64 id, global::System.String tid, global::System.String name, global::System.String createdBy, global::System.String modifiedBy, global::System.DateTimeOffset created, global::System.DateTimeOffset modified)
        {
            AuditTrail auditTrail = new AuditTrail();
            auditTrail.EntityId = entityId;
            auditTrail.EntityType = entityType;
            auditTrail.EntityState = entityState;
            auditTrail.Original = original;
            auditTrail.Current = current;
            auditTrail.Id = id;
            auditTrail.Tid = tid;
            auditTrail.Name = name;
            auditTrail.CreatedBy = createdBy;
            auditTrail.ModifiedBy = modifiedBy;
            auditTrail.Created = created;
            auditTrail.Modified = modified;
            return auditTrail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EntityId
        {
            get
            {
                return _EntityId;
            }
            set
            {
                OnEntityIdChanging(value);
                ReportPropertyChanging("EntityId");
                _EntityId = value;
                ReportPropertyChanged("EntityId");
                OnEntityIdChanged();
            }
        }
        private global::System.String _EntityId;
        partial void OnEntityIdChanging(global::System.String value);
        partial void OnEntityIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EntityType
        {
            get
            {
                return _EntityType;
            }
            set
            {
                OnEntityTypeChanging(value);
                ReportPropertyChanging("EntityType");
                _EntityType = value;
                ReportPropertyChanged("EntityType");
                OnEntityTypeChanged();
            }
        }
        private global::System.String _EntityType;
        partial void OnEntityTypeChanging(global::System.String value);
        partial void OnEntityTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        new public global::System.String EntityState
        {
            get
            {
                return _EntityState;
            }
            set
            {
                OnEntityStateChanging(value);
                ReportPropertyChanging("EntityState");
                _EntityState = value;
                ReportPropertyChanged("EntityState");
                OnEntityStateChanged();
            }
        }
        private global::System.String _EntityState;
        partial void OnEntityStateChanging(global::System.String value);
        partial void OnEntityStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Original
        {
            get
            {
                return _Original;
            }
            set
            {
                OnOriginalChanging(value);
                ReportPropertyChanging("Original");
                _Original = value;
                ReportPropertyChanged("Original");
                OnOriginalChanged();
            }
        }
        private global::System.String _Original;
        partial void OnOriginalChanging(global::System.String value);
        partial void OnOriginalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Current
        {
            get
            {
                return _Current;
            }
            set
            {
                OnCurrentChanging(value);
                ReportPropertyChanging("Current");
                _Current = value;
                ReportPropertyChanged("Current");
                OnCurrentChanged();
            }
        }
        private global::System.String _Current;
        partial void OnCurrentChanging(global::System.String value);
        partial void OnCurrentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tid
        {
            get
            {
                return _Tid;
            }
            set
            {
                OnTidChanging(value);
                ReportPropertyChanging("Tid");
                _Tid = value;
                ReportPropertyChanged("Tid");
                OnTidChanged();
            }
        }
        private global::System.String _Tid;
        partial void OnTidChanging(global::System.String value);
        partial void OnTidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = value;
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = value;
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = value;
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = value;
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTimeOffset Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = value;
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTimeOffset _Created;
        partial void OnCreatedChanging(global::System.DateTimeOffset value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTimeOffset Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = value;
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private global::System.DateTimeOffset _Modified;
        partial void OnModifiedChanging(global::System.DateTimeOffset value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LightSwitchApplication", Name="Endpoint")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Endpoint : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Endpoint object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="tid">Initial value of the Tid property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="version">Initial value of the Version property.</param>
        /// <param name="routeTemplate">Initial value of the RouteTemplate property.</param>
        /// <param name="routePrefix">Initial value of the RoutePrefix property.</param>
        /// <param name="serverRole">Initial value of the ServerRole property.</param>
        /// <param name="priority">Initial value of the Priority property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        /// <param name="createdBy">Initial value of the CreatedBy property.</param>
        /// <param name="modified">Initial value of the Modified property.</param>
        /// <param name="modifiedBy">Initial value of the ModifiedBy property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        public static Endpoint CreateEndpoint(global::System.Int64 id, global::System.String tid, global::System.String name, global::System.String version, global::System.String routeTemplate, global::System.String routePrefix, global::System.String serverRole, global::System.Int32 priority, global::System.DateTimeOffset created, global::System.String createdBy, global::System.DateTimeOffset modified, global::System.String modifiedBy, global::System.String address)
        {
            Endpoint endpoint = new Endpoint();
            endpoint.Id = id;
            endpoint.Tid = tid;
            endpoint.Name = name;
            endpoint.Version = version;
            endpoint.RouteTemplate = routeTemplate;
            endpoint.RoutePrefix = routePrefix;
            endpoint.ServerRole = serverRole;
            endpoint.Priority = priority;
            endpoint.Created = created;
            endpoint.CreatedBy = createdBy;
            endpoint.Modified = modified;
            endpoint.ModifiedBy = modifiedBy;
            endpoint.Address = address;
            return endpoint;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = value;
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tid
        {
            get
            {
                return _Tid;
            }
            set
            {
                OnTidChanging(value);
                ReportPropertyChanging("Tid");
                _Tid = value;
                ReportPropertyChanged("Tid");
                OnTidChanged();
            }
        }
        private global::System.String _Tid;
        partial void OnTidChanging(global::System.String value);
        partial void OnTidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = value;
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Version
        {
            get
            {
                return _Version;
            }
            set
            {
                OnVersionChanging(value);
                ReportPropertyChanging("Version");
                _Version = value;
                ReportPropertyChanged("Version");
                OnVersionChanged();
            }
        }
        private global::System.String _Version;
        partial void OnVersionChanging(global::System.String value);
        partial void OnVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RouteTemplate
        {
            get
            {
                return _RouteTemplate;
            }
            set
            {
                OnRouteTemplateChanging(value);
                ReportPropertyChanging("RouteTemplate");
                _RouteTemplate = value;
                ReportPropertyChanged("RouteTemplate");
                OnRouteTemplateChanged();
            }
        }
        private global::System.String _RouteTemplate;
        partial void OnRouteTemplateChanging(global::System.String value);
        partial void OnRouteTemplateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RoutePrefix
        {
            get
            {
                return _RoutePrefix;
            }
            set
            {
                OnRoutePrefixChanging(value);
                ReportPropertyChanging("RoutePrefix");
                _RoutePrefix = value;
                ReportPropertyChanged("RoutePrefix");
                OnRoutePrefixChanged();
            }
        }
        private global::System.String _RoutePrefix;
        partial void OnRoutePrefixChanging(global::System.String value);
        partial void OnRoutePrefixChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ServerRole
        {
            get
            {
                return _ServerRole;
            }
            set
            {
                OnServerRoleChanging(value);
                ReportPropertyChanging("ServerRole");
                _ServerRole = value;
                ReportPropertyChanged("ServerRole");
                OnServerRoleChanged();
            }
        }
        private global::System.String _ServerRole;
        partial void OnServerRoleChanging(global::System.String value);
        partial void OnServerRoleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = value;
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private global::System.Int32 _Priority;
        partial void OnPriorityChanging(global::System.Int32 value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTimeOffset Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = value;
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTimeOffset _Created;
        partial void OnCreatedChanging(global::System.DateTimeOffset value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedBy
        {
            get
            {
                return _CreatedBy;
            }
            set
            {
                OnCreatedByChanging(value);
                ReportPropertyChanging("CreatedBy");
                _CreatedBy = value;
                ReportPropertyChanged("CreatedBy");
                OnCreatedByChanged();
            }
        }
        private global::System.String _CreatedBy;
        partial void OnCreatedByChanging(global::System.String value);
        partial void OnCreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTimeOffset Modified
        {
            get
            {
                return _Modified;
            }
            set
            {
                OnModifiedChanging(value);
                ReportPropertyChanging("Modified");
                _Modified = value;
                ReportPropertyChanged("Modified");
                OnModifiedChanged();
            }
        }
        private global::System.DateTimeOffset _Modified;
        partial void OnModifiedChanging(global::System.DateTimeOffset value);
        partial void OnModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ModifiedBy
        {
            get
            {
                return _ModifiedBy;
            }
            set
            {
                OnModifiedByChanging(value);
                ReportPropertyChanging("ModifiedBy");
                _ModifiedBy = value;
                ReportPropertyChanged("ModifiedBy");
                OnModifiedByChanged();
            }
        }
        private global::System.String _ModifiedBy;
        partial void OnModifiedByChanging(global::System.String value);
        partial void OnModifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = value;
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = value;
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] RowVersion
        {
            get
            {
                return StructuralObject.GetValidValue(_RowVersion);
            }
            set
            {
                OnRowVersionChanging(value);
                ReportPropertyChanging("RowVersion");
                _RowVersion = value;
                ReportPropertyChanged("RowVersion");
                OnRowVersionChanged();
            }
        }
        private global::System.Byte[] _RowVersion;
        partial void OnRowVersionChanging(global::System.Byte[] value);
        partial void OnRowVersionChanged();

        #endregion

    
    }

    #endregion

    
}
